name: Rodar script diário

on:
  workflow_dispatch:
  schedule:
    - cron: '38 18 * * *'  # Executa às 15h35 no horário de Brasília (UTC-3)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo de credenciais
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > src/credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Executar script
        run: node src/index.js
