name: Rodar script diário

on:
  schedule:
    - cron: '30 13 * * *' # 9h UTC todos os dias
    - cron: '30 17 * * *' # 9h UTC todos os dias
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Executar script
        run: node src/index.js

